
version: '3.7'
services:

    mariadb:
        image: 'mariadb:10.6'
        container_name: 'camagru_db'
        working_dir: /app
        volumes:
            - mariadb-data:/var/lib/mysql
        secrets:
            - mysql_password
            - mysql_root_password
        environment:
            MYSQL_DATABASE: camagru
            MYSQL_USER: camagru
            MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
            MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
        ports:
            - '8083:3306'
        restart: always

    webserver:
        depends_on:
            - mariadb
        image: 'nginx:alpine'
        container_name: 'camagru_web'
        working_dir: /app
        secrets:
            - site.crt
            - site.key
        volumes:
            - './app:/app'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'
            - '443:443'
        restart: always

    php-fpm:
        depends_on:
            - mariadb
        build: phpdocker/php-fpm
        container_name: 'camagru_php'
        working_dir: /app
        secrets:
            - mysql_password
            - mysql_root_password
            - site.crt
        volumes:
            - './app:/app'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini'
            - './phpdocker/ssmtp/ssmtp.conf:/etc/ssmtp/ssmtp.conf'
        restart: always

    phpmyadmin:
        depends_on:
            - mariadb
        image: phpmyadmin
        container_name: 'phpmyadmin'
        ports:
            - 8081:80
        environment:
            PMA_HOST: mariadb
secrets:
    mysql_password:
        file: ./secrets/mysql_password.secret
    mysql_root_password:
        file: ./secrets/mysql_root_password.secret
    site.crt:
        file: ./secrets/MyCertificate.crt
    site.key:
        file: ./secrets/MyKey.key
volumes:
    mariadb-data:
        name: camagru-data

# Create secrets with:
# printf "%s" "$(openssl rand -base64 20)" > mysql_password.secret
# printf "%s" "$(openssl rand -base64 20)" > mysql_root_password.secret

# TLS certificate has to be created manually and added as a secret
# openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out MyCertificate.crt -keyout site.key

# Launch with:
# docker stack deploy --compose-file docker-compose.yml camagru