CREATE DATABASE IF NOT EXISTS camagru;
USE camagru;
CREATE TABLE IF NOT EXISTS users(
	`user_id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	username VARCHAR(32) NOT NULL,
	`password` VARCHAR(255) NOT NULL,
	`name` VARCHAR(255) DEFAULT username,
	email VARCHAR(320) NOT NULL,
	profile_image VARCHAR(255) DEFAULT "default.png",
	biography VARCHAR(4096),
	validation_key VARCHAR(255) NOT NULL,
	validated BOOLEAN DEFAULT FALSE,
	password_reset_key VARCHAR(255),
	`admin` BOOLEAN DEFAULT FALSE,
	email_notification BOOLEAN  DEFAULT TRUE,
	join_date DATETIME DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (email, username),
	PRIMARY KEY (`user_id`)
);
CREATE TABLE IF NOT EXISTS posts(
	post_id BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	`user_id` INT(10) UNSIGNED NOT NULL,
	image_file VARCHAR(1024),
	`description` VARCHAR(4096),
	likes INT UNSIGNED DEFAULT 0,
	comments INT UNSIGNED DEFAULT 0,
	creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (post_id)
);
	CREATE TABLE IF NOT EXISTS drafts(
	draft_id BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	image_file VARCHAR(1024),
	`user_id` INT(10) UNSIGNED NOT NULL,
	PRIMARY KEY (draft_id)
);

	CREATE TABLE IF NOT EXISTS comments(
	comment_id BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	post_id BIGINT(10) UNSIGNED NOT NULL,
	`user_id` INT(10) UNSIGNED NOT NULL,
	comment VARCHAR(4096),
	comment_date DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (comment_id)
);

	CREATE TABLE IF NOT EXISTS likes(
	like_id BIGINT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
	post_id BIGINT(10) UNSIGNED NOT NULL,
	`user_id` INT(10) UNSIGNED NOT NULL,
	like_date DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (like_id)
);